// AUTO-GENERATED by scripts/generate-router-files.mjs — do not edit by hand.
// Canonical source: the tool definition data
// (packages/core/src/server/tool-definitions.ts +
// packages/gate-backend/src/mcp-tools/*.ts).
// Regenerated on every `npm run build:plugin`.

/** Every registered built-in transcodes-guard MCP tool name (bare form). */
export const GUARD_TOOL_NAMES: ReadonlySet<string> = new Set([
  'tc_check_project_assets',
  'tc_check_rbac_permission',
  'tc_check_related_origin',
  'tc_create_member',
  'tc_create_resource',
  'tc_create_role',
  'tc_create_stepup_session',
  'tc_echo',
  'tc_get_console_url',
  'tc_get_current_member_id',
  'tc_get_current_organization_id',
  'tc_get_current_project_id',
  'tc_get_integration_guide',
  'tc_get_member',
  'tc_get_member_suspension',
  'tc_get_my_profile',
  'tc_get_project',
  'tc_get_resources',
  'tc_get_roles',
  'tc_get_security_logs',
  'tc_inspect_stepup_state',
  'tc_jwk_backup',
  'tc_list_authenticators',
  'tc_list_member_devices',
  'tc_list_members_paginated',
  'tc_list_passkeys',
  'tc_list_totps',
  'tc_membership_create_checkout_session',
  'tc_membership_customer_status_by_organization',
  'tc_membership_customer_status_by_project',
  'tc_membership_plans',
  'tc_membership_plans_limits',
  'tc_passcode_create',
  'tc_poll_stepup_session',
  'tc_poll_stepup_session_wait',
  'tc_project_pwa_auth_console',
  'tc_retire_member',
  'tc_retire_resource',
  'tc_retire_role',
  'tc_set_role_permissions',
  'tc_simulate_command',
  'tc_simulate_hook_invocation',
  'tc_simulate_tool_call',
  'tc_suspend_member',
  'tc_unsuspend_member',
  'tc_update_member',
  'tc_update_member_role',
  'tc_update_resource',
  'tc_update_role',
  'tc_user_create',
  'tc_user_find',
  'tc_user_get_current',
]);

/**
 * Step-up infrastructure (meta) tools — systemically required for the
 * step-up recovery loop. Must mirror the backend `guard.meta-tools.ts`
 * exactly; the drift alarm is packages/core/test/meta-tool-names.test.ts.
 */
export const GUARD_META_TOOL_NAMES: ReadonlySet<string> = new Set([
  'tc_create_stepup_session',
  'tc_inspect_stepup_state',
  'tc_poll_stepup_session',
  'tc_poll_stepup_session_wait',
]);
