// AUTO-GENERATED by scripts/generate-router-files.mjs — do not edit by hand.
// Canonical source: the tool definition data
// (packages/core/src/server/tool-definitions.ts +
// packages/gate-backend/src/mcp-tools/*.ts).
// Regenerated on every `npm run build:plugin`.

import type { RbacAction } from './rbac.js';

/** Every registered built-in transcodes-guard MCP tool name (bare form). */
export const GUARD_TOOL_NAMES: ReadonlySet<string> = new Set([
  'tc_check_project_assets',
  'tc_check_rbac_permission',
  'tc_check_related_origin',
  'tc_create_member',
  'tc_create_resource',
  'tc_create_role',
  'tc_create_stepup_session',
  'tc_echo',
  'tc_get_console_url',
  'tc_get_current_member_id',
  'tc_get_current_organization_id',
  'tc_get_current_project_id',
  'tc_get_integration_guide',
  'tc_get_member',
  'tc_get_member_suspension',
  'tc_get_my_profile',
  'tc_get_project',
  'tc_get_resources',
  'tc_get_roles',
  'tc_get_security_logs',
  'tc_inspect_stepup_state',
  'tc_jwk_backup',
  'tc_list_authenticators',
  'tc_list_member_devices',
  'tc_list_members_paginated',
  'tc_list_passkeys',
  'tc_list_totps',
  'tc_membership_create_checkout_session',
  'tc_membership_customer_status_by_organization',
  'tc_membership_customer_status_by_project',
  'tc_membership_plans',
  'tc_membership_plans_limits',
  'tc_passcode_create',
  'tc_poll_stepup_session',
  'tc_poll_stepup_session_wait',
  'tc_project_pwa_auth_console',
  'tc_retire_member',
  'tc_retire_resource',
  'tc_retire_role',
  'tc_set_role_permissions',
  'tc_simulate_command',
  'tc_simulate_hook_invocation',
  'tc_simulate_tool_call',
  'tc_suspend_member',
  'tc_unsuspend_member',
  'tc_update_member',
  'tc_update_member_role',
  'tc_update_resource',
  'tc_update_role',
  'tc_user_create',
  'tc_user_find',
  'tc_user_get_current',
]);

/**
 * Step-up infrastructure (meta) tools — systemically required for the
 * step-up recovery loop. Must mirror the backend `guard.meta-tools.ts`
 * exactly; the drift alarm is packages/core/test/meta-tool-names.test.ts.
 */
export const GUARD_META_TOOL_NAMES: ReadonlySet<string> = new Set([
  'tc_create_stepup_session',
  'tc_inspect_stepup_state',
  'tc_poll_stepup_session',
  'tc_poll_stepup_session_wait',
]);

/** System step-up rule derived from a `stepUp` declaration. */
export interface GuardProtectedToolRule {
  id: string;
  name: string;
  label: string;
  description: string;
  action: RbacAction;
  resource: string;
}

/**
 * Step-up coordinates of every protected tool, in registration order —
 * the system MCP rule table, derived from the definition data.
 */
export const GUARD_PROTECTED_TOOL_RULES: readonly GuardProtectedToolRule[] = [
  {
    id: 'tc-retire-member',
    name: 'tc_retire_member',
    label: 'Retire member',
    description: 'Permanent member deletion',
    action: 'delete',
    resource: 'system',
  },
  {
    id: 'tc-suspend-member',
    name: 'tc_suspend_member',
    label: 'Suspend member',
    description: 'Member login suspension',
    action: 'update',
    resource: 'system',
  },
  {
    id: 'tc-unsuspend-member',
    name: 'tc_unsuspend_member',
    label: 'Unsuspend member',
    description: 'Member suspension removal',
    action: 'update',
    resource: 'system',
  },
  {
    id: 'tc-create-member',
    name: 'tc_create_member',
    label: 'Create member',
    description: 'New member provisioning',
    action: 'create',
    resource: 'system',
  },
  {
    id: 'tc-update-member',
    name: 'tc_update_member',
    label: 'Update member',
    description: 'Member profile update',
    action: 'update',
    resource: 'system',
  },
  {
    id: 'tc-retire-role',
    name: 'tc_retire_role',
    label: 'Retire role',
    description: 'Permanent role deletion',
    action: 'delete',
    resource: 'system',
  },
  {
    id: 'tc-set-role-permissions',
    name: 'tc_set_role_permissions',
    label: 'Set role permissions',
    description: 'Role permissions matrix reset',
    action: 'update',
    resource: 'system',
  },
  {
    id: 'tc-update-member-role',
    name: 'tc_update_member_role',
    label: 'Update member role',
    description: 'Member role reassignment',
    action: 'update',
    resource: 'system',
  },
  {
    id: 'tc-retire-resource',
    name: 'tc_retire_resource',
    label: 'Retire resource',
    description: 'Permanent RBAC resource deletion',
    action: 'delete',
    resource: 'system',
  },
  {
    id: 'tc-create-role',
    name: 'tc_create_role',
    label: 'Create role',
    description: 'New RBAC role creation',
    action: 'create',
    resource: 'system',
  },
  {
    id: 'tc-update-role',
    name: 'tc_update_role',
    label: 'Update role',
    description: 'RBAC role metadata update',
    action: 'update',
    resource: 'system',
  },
  {
    id: 'tc-create-resource',
    name: 'tc_create_resource',
    label: 'Create resource',
    description: 'New RBAC resource creation',
    action: 'create',
    resource: 'system',
  },
  {
    id: 'tc-update-resource',
    name: 'tc_update_resource',
    label: 'Update resource',
    description: 'RBAC resource metadata update',
    action: 'update',
    resource: 'system',
  },
  {
    id: 'tc-passcode-create',
    name: 'tc_passcode_create',
    label: 'Passcode create',
    description: 'Recovery passcode generation',
    action: 'create',
    resource: 'system',
  },
  {
    id: 'tc-get-security-logs',
    name: 'tc_get_security_logs',
    label: 'Get security logs',
    description: 'Project audit log access',
    action: 'read',
    resource: 'system',
  },
];
